image: docker:19.03.12

stages:
  - test
  - build
  - package
  - deploy

variables:
  CONTAINER_NAME: $SERVICE_NAME
  IMAGE_NAME: $SERVICE_NAME

test:
  image: golang:1.16
  stage: test
  script:
    - go test $(go list ./... | grep -v /vendor/) -v -coverprofile=testCoverage.txt
    - go tool cover -func=testCoverage.txt
  artifacts:
    paths:
      - coverage.out

build-go-application:
  image: golang:1.16
  stage: build
  script:
    - go mod download
    - go mod verify
    - go build -o main
  artifacts:
    paths:
      - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: push
    paths:
      - main

package-docker-image:
  stage: package
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: pull
    paths:
      - main
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME

g238_deploy:
  stage: deploy
  tags:
    - g238
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - docker stop $CONTAINER_NAME || true
    - docker run --rm -d -p $SMS_SERVICE_PORT:$SMS_SERVICE_PORT -e SMS_SERVICE_PORT=$SMS_SERVICE_PORT -e SERVICE_NAME=$SERVICE_NAME -e CONFIG_SERVER=$CONFIG_SERVER -e HOST_IP=$HOST_238_IP --name $CONTAINER_NAME $DOCKER_HUB_ID/$IMAGE_NAME

g239_deploy:
  stage: deploy
  tags:
    - g239
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - docker stop $CONTAINER_NAME || true
    - docker run --rm -d -p $SMS_SERVICE_PORT:$SMS_SERVICE_PORT -e SMS_SERVICE_PORT=$SMS_SERVICE_PORT -e SERVICE_NAME=$SERVICE_NAME -e CONFIG_SERVER=$CONFIG_SERVER -e HOST_IP=$HOST_239_IP --name $CONTAINER_NAME $DOCKER_HUB_ID/$IMAGE_NAME

g240_deploy:
  stage: deploy
  tags:
    - g240
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - docker stop $CONTAINER_NAME || true
    - docker run --rm -d -p $SMS_SERVICE_PORT:$SMS_SERVICE_PORT -e SMS_SERVICE_PORT=$SMS_SERVICE_PORT -e SERVICE_NAME=$SERVICE_NAME -e CONFIG_SERVER=$CONFIG_SERVER -e HOST_IP=$HOST_240_IP --name $CONTAINER_NAME $DOCKER_HUB_ID/$IMAGE_NAME