image: docker:19.03.12

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_NAME: $SERVICE_NAME
  IMAGE_NAME: $SERVICE_NAME
  ENVIROMENT: staging

test:
  image: golang:1.16
  stage: test
  script:
    - go test -v -coverprofile=coverage.out ./...
  artifacts:
    paths:
      - coverage.out

build-go-application:
  image: golang:1.16
  stage: build
  script:
    - go mod download
    - go mod verify
    - go build -o main
  artifacts:
    paths:
      - ./main
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: push
    paths:
      - ./main


build-docker-image:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    policy: pull
    paths:
      - ./main
  script:
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME
  environment:
    name: $ENVIROMENT

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - docker stop $CONTAINER_NAME || true
    - docker run --rm -d -p $SMS_SERVICE_PORT:$SMS_SERVICE_PORT -e SMS_SERVICE_PORT=$SMS_SERVICE_PORT -e SERVICE_NAME=$SERVICE_NAME -e CONFIG_SERVER=$CONFIG_SERVER --network $DOCKER_NETWORK --name $CONTAINER_NAME $DOCKER_HUB_ID/$IMAGE_NAME
  environment:
    name: $ENVIROMENT
    url: $STAGING_SERVER